spring.main.web-application-type=none

# Banner configuration
spring.banner.location=classpath:banner.txt
spring.banner.charset=UTF-8
spring.main.banner-mode=console

# Spring Shell configuration
spring.shell.interactive.enabled=true
spring.shell.script.enabled=false
spring.shell.history.enabled=true

# JLine terminal configuration
jline.terminal=org.jline.terminal.impl.ExecPty
jline.terminal.exec=true

# Spring AI configuration
spring.ai.chat.client.enabled=false
spring.ai.model.chat=false
spring.ai.model.embedding=ollama
spring.ai.model.image=false
spring.ai.model.audio.speech=false
spring.ai.model.audio.transcription=false
spring.ai.model.moderation=false


logging.level.root=warn