spring:
  main:
    web-application-type: none
    banner-mode: console
  banner:
    location: classpath:banner.txt
    charset: UTF-8
  shell:
    interactive:
      enabled: true
    script:
      enabled: false
    history:
      enabled: true
    terminal-width: 120
    terminal-height: 30
    prompt: ">"
    output:
      ansi:
        enabled: detect
    input:
      ansi:
        enabled: detect
  ai:
    chat:
      client:
        enabled: false
    model:
      chat: false
      embedding: ollama
      image: false
      audio:
        speech: false
        transcription: false
      moderation: false

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

jline:
  terminal:
    exec=true


logging:
  level:
    root: warn
  charset:
    console: UTF-8
    file: UTF-8
