#!/usr/bin/env python3
"""Native-image auto-fix loop.
Run:  uv run --no-project python tools/native-fix-loop.py [--max-iters N]
"""
import re, subprocess, sys, argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
APP_BUILD = ROOT / "app" / "build"
ARGS_FILE = APP_BUILD / "auto-init-at-build-time.args"
TASK = ":app:nativeCompile"

# ---- 错误模式 -> 修复规则表 ----
# 每项: name, 正则, 从 match 生成 native-image 参数(返回 None 则忽略)
RULES = [
    {
        "name": "image-heap-run-time-object",
        # 典型：An object of type 'org.xml.sax.helpers.AttributesImpl' was found
        #      in the image heap. ... marked for initialization at image run time
        "pattern": re.compile(
            r"An object of type '([\w.$]+)' was found in the image heap",
            re.IGNORECASE,
        ),
        "fix": lambda m: f"--initialize-at-build-time={m.group(1)}",
    },
]

# 记录但不自动注入（需人工/项目级配置，避免盲目修复掩盖真问题）
REPORT_ONLY = [
    re.compile(r"Detected a FileDescriptor in the image heap", re.IGNORECASE),
    re.compile(r"Classes that should be initialized at run time got initialized",
               re.IGNORECASE),
    re.compile(r"is instantiated reflectively but no metadata was found", re.IGNORECASE),
]


def load_existing() -> set:
    if not ARGS_FILE.exists():
        return set()
    return {l.strip() for l in ARGS_FILE.read_text(encoding="utf-8").splitlines()
            if l.strip() and not l.strip().startswith("#")}


def save(existing: set) -> None:
    ARGS_FILE.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Auto-generated by native-fix-loop.py", "# 追加于每次失败后的规则匹配；勿手改，可安全删除重建。"]
    for a in sorted(existing):
        lines.append(a)
    ARGS_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def run_build(task: str = TASK) -> tuple:
    cmd = [str(ROOT / "gradlew.bat"), task, "-x", "test", "--console=plain"]
    out: list[str] = []
    p = subprocess.Popen(cmd, cwd=str(ROOT), stdout=subprocess.PIPE,
                         stderr=subprocess.STDOUT, text=True,
                         encoding="utf-8", errors="replace", bufsize=1)
    assert p.stdout is not None
    # 逐行实时回显编译日志，同时累积以便后续规则匹配
    for line in p.stdout:
        print(line, end="", flush=True)
        out.append(line)
    rc = p.wait()
    return rc, "".join(out)


def parse_fixes(output: str, existing: set) -> set:
    new = set()
    for rule in RULES:
        for m in rule["pattern"].finditer(output):
            try:
                fix = rule["fix"](m)
            except Exception:
                fix = None
            if fix and fix not in existing:
                new.add(fix)
    return new


def parse_report_only(output: str) -> list:
    return [p.pattern for p in REPORT_ONLY if p.search(output)]

def main() -> int:
    ap = argparse.ArgumentParser(description="Auto-fix native-image build errors in a loop.")
    ap.add_argument("--max-iters", type=int, default=20)
    ap.add_argument("--task", default=TASK)
    ap.add_argument("--keep-args", action="store_true",
                    help="保留已有 auto-args 文件不清空（默认每次启动先清空重来）")
    args = ap.parse_args()

    existing = load_existing() if args.keep_args else set()
    if not args.keep_args and ARGS_FILE.exists():
        ARGS_FILE.unlink()
    print(f"[loop] 目标任务 {args.task} | 已累积修复 {len(existing)} 条")

    for it in range(1, args.max_iters + 1):
        print(f"[loop] ====== 迭代 {it}/{args.max_iters}: native 构建开始 ======", flush=True)
        rc, out = run_build(args.task)
        if rc == 0:
            print("[loop] BUILD SUCCESSFUL ✅ 镜像已生成")
            if existing:
                print("[loop] 最终自动修复参数 (" + str(len(existing)) + "):")
                for f in sorted(existing):
                    print("   " + f)
            return 0

        new = parse_fixes(out, existing)
        if new:
            existing |= new
            save(existing)
            print(f"[loop] 本次失败应用 {len(new)} 条修复:")
            for f in sorted(new):
                print("      + " + f)
            print("[loop] 立即重建...")
            continue

        reports = parse_report_only(out)
        if reports:
            print("[loop] 检测到需人工/项目级配置的错误类别（未自动注入）:")
            for r in reports:
                print("      ! " + r)
        tail = "\n".join(out.splitlines()[-35:])
        print(f"[loop] 无新规则可应用，构建仍失败 (rc={rc})。输出末尾:\n{tail}")
        return rc

    print("[loop] 达到最大迭代次数，仍未成功。")
    return 1


if __name__ == "__main__":
    sys.exit(main())
